"""add attendance fields to pairs

Revision ID: aae7637100c0
Revises: f4e21de83c1d
Create Date: 2025-11-25 13:12:00.638085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae7637100c0'
down_revision: Union[str, Sequence[str], None] = 'f4e21de83c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solo_sipper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_solo_sipper_id'), 'solo_sipper', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solo_sipper_id'), table_name='solo_sipper')
    op.drop_table('solo_sipper')
    # ### end Alembic commands ###
