"""add attendance fields to pairs

Revision ID: f4e21de83c1d
Revises: 40246b3349b9
Create Date: 2025-11-25 12:35:54.688247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e21de83c1d'
down_revision: Union[str, Sequence[str], None] = '40246b3349b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairs', sa.Column('member1_attended', sa.Boolean(), nullable=True))
    op.add_column('pairs', sa.Column('member2_attended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairs', 'member2_attended')
    op.drop_column('pairs', 'member1_attended')
    # ### end Alembic commands ###
